# --------------------
# Docker build command
# --------------------
# docker build -f Dockerfile.dev .

# Specify a base image
FROM node:alpine

# Specify a working directory
WORKDIR /app

# Install some dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install
COPY . .

# Default command
CMD ["yarn", "start"]