# --------------------
# Docker build command
# --------------------
# docker build -f Dockerfile.dev .

# ------------------
# Docker run command
# ------------------
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image_id>

# Specify a base image
FROM node:alpine

# Specify a working directory
WORKDIR /app

# Install some dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . .

# Default command
CMD ["yarn", "start"]